inherit_from: .rubocop_todo.yml

AllCops:
  # 除外するディレクトリ（自動生成されたファイル）
  # デフォルト設定にある"vendor/**/*"が無効化されないように記述
  Exclude:
    - 'bin/*'
    - 'lib/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/**'
  # Rails向けのRails copsを実行。"rubocop -R"と同じ
  Rails:
    enabled: true

# "クラスとモジュールのトップレベルのドキュメントが欠落していないかどうかを確認"を無効
Style/Documentation:
  Enabled: false

# "コメント内の非ASCII文字 (英語以外) をチェックします。許可された非ASCII文字の配列をAllowedChars属性に設定できます（デフォルトでは空）"を無効
AsciiComments:
  Enabled: false

# "引用符の使用が構成された設定と一致するかどうかを確認"を無効
Style/StringLiterals:
  Enabled: false

# "Line is too long"を無効
# Metrics/LineLength:
#   Enabled: false

# join_roomの記述が引っかかる為。省略は難しい
# Etrics/MethodLength:
#   Enabled: true
#   Max: 18









#'frozen_string_literal: true'を無効
Style/FrozenStringLiteralComment:
  Enabled: false

# tweet_searchやtestのnamespaceが引っかかるため
Style/ClassAndModuleChildren:
  Enabled: false

# 線が多い長いブロックは避けてください
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# NotificationsControllerが22文字の為
Metrics/AbcSize:
  Enabled: true
  Max: 23

# if~else~endの方がひと目で分かりやすいと思うためfalse。詳細は以下を参照
# https://docs.rubocop.org/rubocop/cops_style.html#styleguardclause
Style/GuardClause:
  Enabled: false

# devise_helperの関係のため
Naming/HeredocDelimiterNaming:
  Enabled: false